DROP TABLE IF EXISTS automobili CASCADE;
DROP TABLE IF EXISTS modelli CASCADE;
DROP TABLE IF EXISTS marche CASCADE;
DROP TABLE IF EXISTS regioni CASCADE;
DROP TABLE IF EXISTS stati CASCADE;
DROP TABLE IF EXISTS alimentazioni CASCADE;
DROP TABLE IF EXISTS utenti CASCADE;

